from properties import vwl_hold, vbl_hold, vblneg_hold, w_ax_range
from properties import vdd_seevinck
from properties import vsweep_seevinck
from properties import rit_models, dc_vsweep_seevinck, snm_max, snm_min, w_ax_step_param_seevinck, save_w_ax_seevinck
from utils.path import ltspice, schematics, images, data
from utils.patterns import w_ax_seevinck_pattern, snm_max_seevinck_pattern, snm_min_seevinck_pattern
from models.snm import graphical_processing, rotate_points, seevinck_processing, RequestPlot
from models.ops import save_image, get_data, __init_model__, CircuitType, OperationType, RequestPlotSchematic
from matplotlib import pyplot as plt
import os
from properties import w_ax_pos


def seevinck_hold_snm_analysis():
    (
        steps,
        vsweep_seevinck_hold,
        i_leaks_seevinck_hold,
        v_1_seevinck_hold,
        v_2_seevinck_hold,
        v_dd_seevinck_hold,
        v_wl_seevinck_hold,
        v_bl_seevinck_hold,
        v_blneg_seevinck_hold,
        seevinck_hold_log
    ) = __init_model__(
        operation_type=OperationType.HOLD,
        circuit_type=CircuitType.SEEVINCK,
        asc_file_path=os.path.join(ltspice, "seevinck/hold/seevinck_hold.asc"),
        schematic_image_path=os.path.join(schematics, "seevinck.png"),
        request_plot_schematic=RequestPlotSchematic.TRUE,
        vdd=vdd_seevinck,
        vsweep=vsweep_seevinck,
        vwl=vwl_hold,
        vbl=vbl_hold,
        vblneg=vblneg_hold,
        params=[rit_models, dc_vsweep_seevinck, snm_max(0.707), snm_min(0.707), w_ax_step_param_seevinck,
                save_w_ax_seevinck]
    )

    plt.figure(figsize=(16, 4))
    vq_seevinck_hold = []
    vqneg_seevinck_hold = []
    vq_vqneg_seevinck_hold = []
    x_seevinck_hold = []
    for step in range(len(steps)):
        vq = v_1_seevinck_hold.get_wave(step)
        vqneg = v_2_seevinck_hold.get_wave(step)
        vq_minus_vqneg = vq - vqneg
        vq_seevinck_hold.append(vq)
        vqneg_seevinck_hold.append(vqneg)
        vq_vqneg_seevinck_hold.append(vq_minus_vqneg)
        x = vsweep_seevinck_hold.get_wave(step)
        x_seevinck_hold.append(x)
        plt.plot(x, vq, label=steps[step], color='blue')
        plt.plot(x, vqneg, label=steps[step], color='green')
        plt.plot(x, vq_minus_vqneg, label=steps[step], color='red')
    plt.title("V(v1), V(v2), V(v1)-V(v2) Curves Hold Phase")
    plt.xlabel("steps");
    plt.ylabel("Hold Voltages")
    plt.legend(["V(v1)", "V(v2)", "V(v1)-V(v2)"])
    save_image(image_path=os.path.join(images, "seevinck_hold_simulation.png"), plt=plt)
    plt.show()

    seevinck_hold_log_file_path = f"./{seevinck_hold_log}"
    with open(seevinck_hold_log_file_path, "r") as file:
        content = file.read()

    w_ax_seevinck_hold = get_data(pattern=w_ax_seevinck_pattern, content=content)

    snm_max_seevinck_hold = get_data(pattern=snm_max_seevinck_pattern, content=content)
    snm_max_seevinck_hold = [1000 * value for value in snm_max_seevinck_hold]

    snm_min_seevinck_hold = get_data(pattern=snm_min_seevinck_pattern, content=content)
    snm_min_seevinck_hold = [abs(1000 * value) for value in snm_min_seevinck_hold]

    print("{:<30} {:<30} {:<30}".format("w_ax", "SNM_MAX(HOLD)", "SNM_MIN(HOLD)"))
    for w, smax, smin in zip(w_ax_seevinck_hold, snm_max_seevinck_hold, snm_min_seevinck_hold):
        print("{:<30} {:<30} {:<30}".format(f'{w} u', f'{smax} mV', f'{smin} mV'))

    snm_seevinck_hold = []
    for snm_max_hold, snm_min_hold in zip(snm_max_seevinck_hold, snm_min_seevinck_hold):
        if snm_max_hold > snm_min_hold:
            snm_seevinck_hold.append(snm_min_hold)
        else:
            snm_seevinck_hold.append(snm_max_hold)

    print(f'snm_seevinck_hold[{w_ax_seevinck_hold[w_ax_pos]} u] = {snm_seevinck_hold[w_ax_pos]}')

    plt.figure(figsize=(16, 4))
    plt.plot(w_ax_seevinck_hold, snm_max_seevinck_hold)
    plt.plot(w_ax_seevinck_hold, snm_min_seevinck_hold)
    plt.xlabel("w_ax");
    plt.ylabel("snm")
    plt.legend(["snm_max", "snm_min"])
    plt.title("SNM SEEVINCK HOLD GENERATED BY LTSPICE")
    save_image(image_path=os.path.join(images, "snm_seevinck_hold_generated_by_ltspice.png"), plt=plt)
    plt.show()


    fig, axs = plt.subplots(1, 3, figsize=(16, 6))

    snm_seevinck_hold_seevinck_processing = []
    snm_seevinck_hold_standard_processing = []

    for w in range(w_ax_range):

        # vq-vqneg rotating
        for vq_array, vqneg_array in zip(vq_seevinck_hold, vqneg_seevinck_hold):
            vq_vqneg_array = vq_array - vqneg_array
            x_diff, y_diff = rotate_points(x=x_seevinck_hold[w], y=vq_vqneg_array, angle_degrees=-45)
            axs[0].plot(x_diff, y_diff, color='red')
        axs[0].set_title("V(v1)-V(v2) Curve Hold Phase")
        axs[0].legend(["V(v1) - V(v2)"])

        # vq and vqneg rotating
        xshold1, yshold1 = rotate_points(x=x_seevinck_hold[w], y=vq_seevinck_hold[w], angle_degrees=-45)
        xshold2, yshold2 = rotate_points(x=x_seevinck_hold[w], y=vqneg_seevinck_hold[w], angle_degrees=-45)
        axs[1].plot(xshold1, yshold1, color='blue')
        axs[1].plot(xshold2, yshold2, color='green')

        # seevinck processing
        snm_seevinck_hold_seevinck_processing_value = seevinck_processing(
            x_v1_minus_v2=x_seevinck_hold[w],
            v1_minus_v2=vq_vqneg_seevinck_hold[w],
            ax=axs[1],
            request_text_plot=RequestPlot.FALSE
        )
        snm_seevinck_hold_seevinck_processing.append(snm_seevinck_hold_seevinck_processing_value)

        # graphical-processing
        snm_seevinck_hold_standard_processing_value = graphical_processing(
            x_vq=xshold1,
            vq=yshold1,
            x_vqneg=xshold2,
            vqneg=yshold2,
            ax=axs[1],
            request_text_plot=RequestPlot.FALSE
        )
        snm_seevinck_hold_standard_processing.append(snm_seevinck_hold_standard_processing_value)

    axs[1].set_title("V(v1)-V(v2) Curve Hold Phase and SNM")
    axs[1].grid()

    # vq-vqneg rotating
    for vq_array, vqneg_array in zip(vq_seevinck_hold, vqneg_seevinck_hold):
        vq_vqneg_array = vq_array - vqneg_array
        x_diff, y_diff = rotate_points(x=x_seevinck_hold[w_ax_pos], y=vq_vqneg_array, angle_degrees=-45)
        axs[0].plot(x_diff, y_diff, color='red')
    axs[2].set_title("V(v1)-V(v2) Curve Hold Phase")
    axs[2].legend(["V(v1) - V(v2)"])

    # vq and vqneg rotating
    xshold1, yshold1 = rotate_points(x=x_seevinck_hold[w_ax_pos], y=vq_seevinck_hold[w_ax_pos], angle_degrees=-45)
    xshold2, yshold2 = rotate_points(x=x_seevinck_hold[w_ax_pos], y=vqneg_seevinck_hold[w_ax_pos],
                                     angle_degrees=-45)
    axs[2].plot(xshold1, yshold1, color='blue')
    axs[2].plot(xshold2, yshold2, color='green')


    # seevinck processing
    snm_seevinck_hold_seevinck_processing_w_ax = seevinck_processing(
        x_v1_minus_v2=x_seevinck_hold[w_ax_pos],
        v1_minus_v2=vq_vqneg_seevinck_hold[w_ax_pos],
        ax=axs[2],
        request_text_plot=RequestPlot.TRUE
    )

    # graphical-processing
    snm_seevinck_hold_standard_processing_w_ax = graphical_processing(
        x_vq=xshold1,
        vq=yshold1,
        x_vqneg=xshold2,
        vqneg=yshold2,
        ax=axs[2],
        request_text_plot=RequestPlot.TRUE
    )

    axs[2].set_title("V(v1)-V(v2) Curve Hold Phase and SNM")
    axs[2].grid()

    print("{:<30} {:<30} {:<30}".format("w_ax", "snm(hold)_seevinck", "snm(hold)_graphical"))
    for w, snm_hold_seevinck, snm_hold_graphical in zip(w_ax_seevinck_hold, snm_seevinck_hold_seevinck_processing,
                                                        snm_seevinck_hold_standard_processing):
        print("{:<30} {:<30} {:<30}".format(w, snm_hold_seevinck, snm_hold_graphical))

    save_image(image_path=os.path.join(images, "v1_minus_v2_seevinck_hold.png"), plt=plt)
    plt.show()

    w_ax_hold_seevinck_file_path = os.path.join(data, 'out', 'hold', 'snm', 'seevinck', 'wax_hold_seevinck.txt')
    with open(w_ax_hold_seevinck_file_path, 'w') as file:
        for val in w_ax_seevinck_hold:
            file.write(f'{val}\n')

    snm_hold_seevinck_file_path = os.path.join(data, 'out', 'hold', 'snm', 'seevinck', 'snm_hold_seevinck.txt')
    with open(snm_hold_seevinck_file_path, 'w') as file:
        for val in snm_seevinck_hold:
            file.write(f'{val}\n')


if __name__ == "__main__":
    seevinck_hold_snm_analysis()
