from properties import vwl_read, vbl_read, vblneg_read, w_ax_range
from properties import vdd_standard
from properties import vsweep_standard
from properties import rit_models, dc_vsweep_standard, w_ax_step_param_standard, save_w_ax_standard
from utils.path import ltspice, schematics, images
from utils.patterns import w_ax_standard_pattern
from models.snm import graphical_processing, RequestPlot
from models.ops import save_image, get_data, __init_model__, CircuitType, OperationType, RequestPlotSchematic
from matplotlib import pyplot as plt
import os
from properties import w_ax_pos


def standard_read_snm_analysis():
    (
        steps,
        vsweep_standard_read,
        i_leaks_standard_read,
        v_q_standard_read,
        v_q_neg_standard_read,
        v_dd_standard_read,
        v_wl_standard_read,
        v_bl_standard_read,
        v_blneg_standard_read,
        standard_read_log
    ) = __init_model__(
        operation_type=OperationType.READ,
        circuit_type=CircuitType.STANDARD,
        asc_file_path=os.path.join(ltspice, "standard/read/standard_read.asc"),
        schematic_image_path=os.path.join(schematics, "standard.png"),
        request_plot_schematic=RequestPlotSchematic.TRUE,
        vdd=vdd_standard,
        vsweep=vsweep_standard,
        vwl=vwl_read,
        vbl=vbl_read,
        vblneg=vblneg_read,
        params=[rit_models, dc_vsweep_standard, w_ax_step_param_standard, save_w_ax_standard]
    )

    plt.figure(figsize=(16, 4))
    for step in range(len(steps)):
        x = vsweep_standard_read.get_wave(step)
        vq = v_q_standard_read.get_wave(step)
        plt.plot(x, vq, label=steps[step], color='blue')
    plt.title("V(q) Curve Read Phase")
    plt.legend(["V(q)"])
    save_image(image_path=os.path.join(images, "standard_read_simulation.png"), plt=plt)
    plt.show()

    standard_read_log_file_path = f"./{standard_read_log}"

    with open(standard_read_log_file_path, "r") as file:
        content = file.read()

    w_ax_standard_read = get_data(pattern=w_ax_standard_pattern, content=content)
    print(f'w_ax_standard_read = {w_ax_standard_read}')

    plt.figure(figsize=(16, 4))
    plt.legend(['w_ax_standard_read'])
    plt.plot(w_ax_standard_read, label='w_ax_standard_read')
    plt.ylabel('w_min_pmos_read');
    plt.xlabel('steps');
    plt.title('W AX Trend Read Phase')


    fig, axs = plt.subplots(1, 3, figsize=(16, 5))
    x_vq_standard_read = []
    vq_standard_read = []
    x_vqneg_standard_read = []
    vqneg_standard_read = []
    for step in range(len(steps)):
        x = vsweep_standard_read.get_wave(step)
        vq = v_q_standard_read.get_wave(step)
        x_vq_standard_read.append(x)
        vq_standard_read.append(vq)
        x_vqneg_standard_read.append(vq)
        vqneg_standard_read.append(x)
        axs[0].plot(vsweep_standard_read.get_wave(step), v_q_standard_read.get_wave(step), label=steps[step],
                    color='blue')
        axs[0].plot(v_q_standard_read.get_wave(step), vsweep_standard_read.get_wave(step), label=steps[step],
                    color='green')
    axs[0].set_title("Butterfly Curve Read Phase")
    axs[0].legend(["V(q)", "V(q_neg)"])

    # graphical-processing
    print("{:<30} {:<30}".format("w_ax", "SNM(READ)"))
    snm_standard_read = []
    for w in range(w_ax_range):
        snm_standard_read_value = graphical_processing(
            x_vq=x_vq_standard_read[w],
            vq=vq_standard_read[w],
            x_vqneg=x_vqneg_standard_read[w],
            vqneg=vqneg_standard_read[w],
            ax=axs[1],
            request_text_plot=RequestPlot.FALSE
        )
        snm_standard_read.append(snm_standard_read_value)
        print("{:<30} {:<30}".format(w_ax_standard_read[w], snm_standard_read_value))

    snm_standard_read_w_ax = graphical_processing(
        x_vq=x_vq_standard_read[w_ax_pos],
        vq=vq_standard_read[w_ax_pos],
        x_vqneg=x_vqneg_standard_read[w_ax_pos],
        vqneg=vqneg_standard_read[w_ax_pos],
        ax=axs[2],
        request_text_plot=RequestPlot.TRUE
    )
    print(f'snm_standard_read[w_ax_pos={w_ax_standard_read[w_ax_pos]} u] = {snm_standard_read_w_ax}')

    save_image(image_path=os.path.join(images, "butterfly_curve_standard_read.png"), plt=plt)
    plt.show()


    fig_standard_read = plt.figure(figsize=(16, 4))
    plt.plot(w_ax_standard_read, snm_standard_read)
    plt.ylabel("snm")
    plt.xlabel("w_ax")
    plt.title("SNM READ GENERATED BY GRAPHICAL METHOD")
    plt.grid()
    save_image(image_path=os.path.join(images, "snm_standard_read.png"), plt=plt)
    plt.show()

    return (
        w_ax_standard_read,
        snm_standard_read
    )


if __name__ == "__main__":
    standard_read_snm_analysis()
